apiVersion: v1
kind: Service
metadata:
  name: hashctl
  labels:
    app.kubernetes.io/name: hashctl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hashctl
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
